### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by evanxg852000** [AlexEne/rust-chip8#4]
https://github.com/AlexEne/rust-chip8/blob/1f1cf4c61e55c6032a435a78def8c48e919d6b10/src/cpu.rs#L32

what's the impact of changing the `|` to `+` 
as `let instruction: u16 = (hi << 8) + lo;`
I searched for other implementation and saw them using `+`

https://github.com/rylev/Rust-8/blob/master/src/chip8.rs#L288

it gives the same byte encoding but trying to figure out what could be the impact in a broader sence

**Comment by AlexEne** [comment]
For this case, it's exactly the same thing as long as lo and hi are in the correct ranges, then `|` becomes just an addition
