### ISSUE TITLE
Using the code in minifb as example

### ISSUE THREAD

**Issue by emoon** [AlexEne/rust-chip8#6]
Hi,

I'm the author of minifb (that you are using in the code, thanks for that :) I'm currently doing some work on getting the crate to 1.0 https://github.com/emoon/rust_minifb/issues/101 and one of the things I want to do is to have more examples included.

Having an emulator that isn't super complex would fit great as an example and I wonder if you would be fine with me including it in the minifb repo under `examples` ? You will be fully credited for the code of course.

Cheers!

**Comment by AlexEne** [comment]
That's perfectly fine with me, and thanks for this awesome library :D

**Comment by emoon** [comment]
Awesome! Thanks :)

**Comment by AlexEne** [comment]
Closing this, thanks for considering it and ping me if you encounter issues.
